# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/markdownlint/markdownlint
    rev: master # or specific git tag
    hooks:
      - id: markdownlint # Configure in .mdlrc
        args: ["-g"]

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        language: docker_image
        entry: koalaman/shellcheck:stable
        types: [shell]
        args: ["-C"]
      - id: shfmt
        name: shfmt
        language: docker_image
        entry: mvdan/shfmt
        types: [shell]
        args: ["-i", "4", "-ci", "-sr"]
# uncomment below to help debug pre-commit checks
# - repo: meta
#   hooks:
#       - id: check-hooks-apply
#       - id: check-useless-excludes
#       - id: identity
