# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# - repo: https://github.com/jumanjihouse/pre-commit-hooks
#   rev: master  # or specific git tag
#   hooks:
#     - id: forbid-binary
#     - id: git-check  # Configure in .gitattributes
#     - id: markdownlint # Configure in .mdlrc

- repo: local
  hooks:
      - id: shellcheck
        name: shellcheck
        language: docker_image
        entry: koalaman/shellcheck:stable
        types: [shell]
        args: ["-C"]
      - id: shfmt
        name: shfmt
        language: docker_image
        entry: mvdan/shfmt
        types: [shell]
        args: ["-i", "4", "-ci", "-sr"]

# uncomment below to help debug pre-commit checks
# - repo: meta
#   hooks:
#       - id: check-hooks-apply
#       - id: check-useless-excludes
#       - id: identity
